TASK-7:Creating Views
  
CREATE VIEW EMP_VIEW AS SELECT EMPNO,ENAME,SAL FROM EMP;

SELECT * FROM EMP_VIEW

CREATE VIEW HIGH_SAL AS SELECT EMPNO,ENAME,SAL FROM EMP WHERE SAL > 3000;

SELECT * FROM HIGH_SAL;

CREATE VIEW EMP_DEPT_VIEW AS SELECT E.EMPNO,E.ENAME,E.SAL,D.DNAME FROM EMP E JOIN DEPT D ON E.DEPTNO = D.DEPTNO;

SELECT * FROM EMP_DEPT_VIEW;
 
CREATE VIEW EMP_BONES AS SELECT EMPNO,ENAME,SAL,SAL * 0.10 NEW_SAL FROM EMP;

SELECT * FROM EMP_BONES;

CREATE VIEW DEPT_AVG AS SELECT DEPTNO,AVG(SAL) AS AVG_SAL FROM EMP GROUP BY DEPTNO;

SELECT * FROM DEPT_AVG;

CREATE VIEW EMP_HIGH_SAL AS SELECT * FROM HIGH_SAL WHERE SAL > 4000;

DROP VIEW EMP_HIGH_SAL;

SELECT * FROM EMP_HIGH_SAL;

CREATE VIEW EMP_SIMPLE AS SELECT EMPNO,ENAME,JOB FROM EMP;

SELECT * FROM EMP_SIMPLE;

CREATE VIEW TOP_3 AS SELECT * FROM (SELECT EMPNO,ENAME,SAL FROM EMP ORDER BY SAL DESC) WHERE ROWNUM <= 3;

SELECT * FROM TOP_3;

CREATE VIEW DEPT_SAL AS SELECT DEPTNO,COUNT(*) AS TOTAL_EMP, SUM(SAL) AS TOTAL_SAL, AVG(SAL) AS AVG_SAL FROM EMP GROUP BY DEPTNO;

SELECT *  FROM DEPT_SAL;

CREATE VIEW AVG_EMPS AS SELECT EMPNO,ENAME,SAL FROM EMP WHERE SAL>(SELECT AVG(SAL) FROM EMP);

SELECT * FROM AVG_EMPS;

CREATE VIEW emp_dept_detail AS SELECT E.EMPNO,E.ENAME,E.JOB,E.SAL,D.DNAME,D.LOC FROM EMP E JOIN DEPT D ON E.DEPTNO=D.DEPTNO;

SELECT * FROM EMP_DEPT_DETAIL;

CREATE VIEW EMP_WITHOUT_MGR AS SELECT EMPNO,ENAME,JOB FROM EMP WHERE MGR IS NULL;

SELECT * FROM EMP_WITHOUT_MGR;

DROP VIEW EMP_WITHOUT_MGR;






